"""Agora tem grupos

Revision ID: 0514720a76aa
Revises: 16938c8aa719
Create Date: 2021-09-10 19:52:17.551490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0514720a76aa'
down_revision = '16938c8aa719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo')),
    sa.UniqueConstraint('nome', name=op.f('uq_grupo_nome'))
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuario_grupo_id_grupo'), 'grupo', ['grupo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuario_grupo_id_grupo'), type_='foreignkey')
        batch_op.drop_column('grupo_id')

    op.drop_table('grupo')
    # ### end Alembic commands ###
