"""Versao inicial do banco

Revision ID: 16938c8aa719
Revises: 
Create Date: 2021-09-10 19:40:30.472508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16938c8aa719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('nick', name=op.f('uq_usuario_nick'))
    )
    op.create_table('conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest'], ['usuario.id'], name=op.f('fk_conversa_dest_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversa'))
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rem', sa.String(length=20), nullable=True),
    sa.Column('msg', sa.String(length=144), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name=op.f('fk_mensagem_conversa_id_conversa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('conversa')
    op.drop_table('usuario')
    # ### end Alembic commands ###
